export const placesImages = [
  {
    id: "1b",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Restaurant",
  },
  {
    id: "2b",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Cottage",
  },
  {
    id: "3b",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Castle",
  },
  {
    id: "4b",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Fantast city",
  },
  {
    id: "5b",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "beach",
  },
  {
    id: "6b",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Carbins",
  },
  {
    id: "7b",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Off-grid",
  },
  {
    id: "8b",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Farm",
  },
  {
    id: "9b",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Restaurant",
  },
  {
    id: "10b",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Farm",
  },
  {
    id: "11b",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Off-grid",
  },
  {
    id: "12b",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "beach",
  },
  {
    id: "13b",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Cottage",
  },
  {
    id: "14b",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Restaurant",
  },
  {
    id: "15b",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Carbins",
  },
  {
    id: "16b",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Castle",
  },
];
