export const placesImages = [
  {
    id: "https://res.cloudinary.com/praiseobende/image/upload/v1668427113/1b_jzww4e.svg",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Restaurant",
  },
  {
    id: "https://res.cloudinary.com/praiseobende/image/upload/v1668427119/2b_ecp9p5.svg",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Cottage",
  },
  {
    id: "https://res.cloudinary.com/praiseobende/image/upload/v1668427114/3b_cshuir.svg",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Castle",
  },
  {
    id: "https://res.cloudinary.com/praiseobende/image/upload/v1668427121/4b_zjnacb.svg",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Fantast city",
  },
  {
    id: "https://res.cloudinary.com/praiseobende/image/upload/v1668427117/5b_dqimrd.svg",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "beach",
  },
  {
    id: "https://res.cloudinary.com/praiseobende/image/upload/v1668427118/6b_jh2lpu.svg",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Carbins",
  },
  {
    id: "https://res.cloudinary.com/praiseobende/image/upload/v1668427149/7b_tbrfmm.svg",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Off-grid",
  },
  {
    id: "https://res.cloudinary.com/praiseobende/image/upload/v1668427130/8b_swm1qf.svg",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Farm",
  },
  {
    id: "https://res.cloudinary.com/praiseobende/image/upload/v1668427127/9b_jow4it.svg",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Restaurant",
  },
  {
    id: "https://res.cloudinary.com/praiseobende/image/upload/v1668427131/10b_tlfowe.svg",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Farm",
  },
  {
    id: "https://res.cloudinary.com/praiseobende/image/upload/v1668427128/11b_nzv7ry.svg",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Off-grid",
  },
  {
    id: "https://res.cloudinary.com/praiseobende/image/upload/v1668427132/12b_vv4n19.svg",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "beach",
  },
  {
    id: "https://res.cloudinary.com/praiseobende/image/upload/v1668427140/13b_j0sdcw.svg",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Cottage",
  },
  {
    id: "https://res.cloudinary.com/praiseobende/image/upload/v1668427147/14b_omelrs.svg",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Restaurant",
  },
  {
    id: "https://res.cloudinary.com/praiseobende/image/upload/v1668427149/15b_jqlhvk.svg",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Carbins",
  },
  {
    id: "https://res.cloudinary.com/praiseobende/image/upload/v1668427146/16b_uwrhpp.svg",
    name: "Desert king",
    price: "1MBT per night",
    distance: "2345km away",
    duration: "available for 2weeks stay",
    type: "Castle",
  },
];
